name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get short SHA
        id: shortsha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker buildx build --push --platform linux/amd64 --tag ghcr.io/${{ github.repository }}:${{ steps.shortsha.outputs.sha }} --tag ghcr.io/${{ github.repository }}:latest .
